name: Deploy Backend

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e

            cd /root/udhari/staging/udhari_backend

            git fetch origin staging
            git reset --hard origin/staging

            cd /root/udhari

            docker compose up -d --build --force-recreate udhari-backend-staging

            docker compose ps
            docker ps